###
# Get All Suits
###
# GET http://localhost:8090/products
GET http://localhost:8090/products
Authorization: Bearer Iw8zeveVyaPNWonPNaU0213uw3g6Ei

###
# Get Suit By ID (Existing Suit)
###
GET http://localhost:8090/products/5268203c-de76-4921-a3e3-439db69c462a
Authorization: Bearer Iw8zeveVyaPNWonPNaU0213uw3g6Ei

<> 2024-05-07T194420.200.json

###
# Get Suit By ID (Non-existent Suit)
###
GET http://localhost:8090/products/non-existent-product-id
Authorization: Bearer Iw8zeveVyaPNWonPNaU0213uw3g6Ei

<> 2024-05-07T194410.404.txt

###
# Reserve Suits (Valid Reservation)
###
POST http://localhost:8090/products/reserve
Authorization: Bearer Iw8zeveVyaPNWonPNaU0213uw3g6Ei
Content-Type: application/json

{
  "5268203c-de76-4921-a3e3-439db69c462a": 2
}

<> 2024-05-07T202135.201.json
<> 2024-05-07T194524.201.json

###
# Reserve Suits (Invalid Suit ID)
###
POST http://localhost:8090/products/reserve
Authorization: Bearer Iw8zeveVyaPNWonPNaU0213uw3g6Ei
Content-Type: application/json

{
  "invalid-product-id": 1
}

<> 2024-05-07T194455.404.txt

###
# Reserve Suits (Insufficient Quantity)
###
POST http://localhost:8090/products/reserve
Authorization: Bearer Iw8zeveVyaPNWonPNaU0213uw3g6Ei
Content-Type: application/json

{
  "5268203c-de76-4921-a3e3-439db69c462a": 10
}

<> 2024-05-07T194515.404.txt

###
# Get Reservation By ID (Existing Reservation)
###
GET http://localhost:8090/reservations/b45da5c8-aaa0-4522-96d6-077f13a42b7e
Authorization: Bearer Iw8zeveVyaPNWonPNaU0213uw3g6Ei

<> 2024-05-07T202111.200.json
<> 2024-05-07T194810.500.json
<> 2024-05-07T194757.500.json
###
# Get Reservation By ID (Non-existent Reservation)
###
GET http://localhost:8090/reservations/non-existent-reservation-id
Authorization: Bearer Iw8zeveVyaPNWonPNaU0213uw3g6Ei

<> 2024-05-07T194841.404.txt

###
# Cancel Reservation (Existing Reservation)
###
POST http://localhost:8090/reservations/037245bf-b9f9-424c-8065-a57898ce84f6/cancel
Authorization: Bearer Iw8zeveVyaPNWonPNaU0213uw3g6Ei

###
# Cancel Reservation (Non-existent Reservation)
###
POST http://localhost:8090/reservations/non-existent-reservation-id/cancel
Authorization: Bearer Iw8zeveVyaPNWonPNaU0213uw3g6Ei

<> 2024-05-07T194734.404.txt

###
# Confirm Reservation (Existing Reservation)
###
POST http://localhost:8090/reservations/b45da5c8-aaa0-4522-96d6-077f13a42b7e/confirm
Authorization: Bearer Iw8zeveVyaPNWonPNaU0213uw3g6Ei

###
# Confirm Reservation (Non-existent Reservation)
###
POST http://localhost:8090/reservations/non-existent-reservation-id/confirm
Authorization: Bearer Iw8zeveVyaPNWonPNaU0213uw3g6Ei

<> 2024-05-07T202221.404.txt
